// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestPb.proto

package com.hirpc.protocol.protobuf;

public final class RequestPb {
  private RequestPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestInnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hirpc.entity.RequestInner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string hirpcVersion = 1;</code>
     * @return Whether the hirpcVersion field is set.
     */
    boolean hasHirpcVersion();
    /**
     * <code>required string hirpcVersion = 1;</code>
     * @return The hirpcVersion.
     */
    String getHirpcVersion();
    /**
     * <code>required string hirpcVersion = 1;</code>
     * @return The bytes for hirpcVersion.
     */
    com.google.protobuf.ByteString
        getHirpcVersionBytes();

    /**
     * <code>required string servicePath = 2;</code>
     * @return Whether the servicePath field is set.
     */
    boolean hasServicePath();
    /**
     * <code>required string servicePath = 2;</code>
     * @return The servicePath.
     */
    String getServicePath();
    /**
     * <code>required string servicePath = 2;</code>
     * @return The bytes for servicePath.
     */
    com.google.protobuf.ByteString
        getServicePathBytes();

    /**
     * <code>required string serviceName = 3;</code>
     * @return Whether the serviceName field is set.
     */
    boolean hasServiceName();
    /**
     * <code>required string serviceName = 3;</code>
     * @return The serviceName.
     */
    String getServiceName();
    /**
     * <code>required string serviceName = 3;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>optional string serviceVersion = 4;</code>
     * @return Whether the serviceVersion field is set.
     */
    boolean hasServiceVersion();
    /**
     * <code>optional string serviceVersion = 4;</code>
     * @return The serviceVersion.
     */
    String getServiceVersion();
    /**
     * <code>optional string serviceVersion = 4;</code>
     * @return The bytes for serviceVersion.
     */
    com.google.protobuf.ByteString
        getServiceVersionBytes();

    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */
    int getHeaderCount();
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */
    boolean containsHeader(
            String key);
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getHeader();
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */
    java.util.Map<String, String>
    getHeaderMap();
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */

    String getHeaderOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */

    String getHeaderOrThrow(
            String key);

    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @return A list containing the parameterTypes.
     */
    java.util.List<String>
        getParameterTypesList();
    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @return The count of parameterTypes.
     */
    int getParameterTypesCount();
    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    String getParameterTypes(int index);
    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParameterTypesBytes(int index);

    /**
     * <code>optional string data = 7;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>optional string data = 7;</code>
     * @return The data.
     */
    String getData();
    /**
     * <code>optional string data = 7;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code com.hirpc.entity.RequestInner}
   */
  public  static final class RequestInner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hirpc.entity.RequestInner)
      RequestInnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestInner.newBuilder() to construct.
    private RequestInner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestInner() {
      hirpcVersion_ = "";
      servicePath_ = "";
      serviceName_ = "";
      serviceVersion_ = "";
      parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      data_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestInner();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestInner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              hirpcVersion_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              servicePath_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              serviceName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              serviceVersion_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                header_ = com.google.protobuf.MapField.newMapField(
                    HeaderDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<String, String>
              header__ = input.readMessage(
                  HeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              header_.getMutableMap().put(
                  header__.getKey(), header__.getValue());
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                parameterTypes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              parameterTypes_.add(bs);
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              data_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          parameterTypes_ = parameterTypes_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestPb.internal_static_com_hirpc_entity_RequestInner_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestPb.internal_static_com_hirpc_entity_RequestInner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestInner.class, Builder.class);
    }

    private int bitField0_;
    public static final int HIRPCVERSION_FIELD_NUMBER = 1;
    private volatile Object hirpcVersion_;
    /**
     * <code>required string hirpcVersion = 1;</code>
     * @return Whether the hirpcVersion field is set.
     */
    public boolean hasHirpcVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string hirpcVersion = 1;</code>
     * @return The hirpcVersion.
     */
    public String getHirpcVersion() {
      Object ref = hirpcVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hirpcVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hirpcVersion = 1;</code>
     * @return The bytes for hirpcVersion.
     */
    public com.google.protobuf.ByteString
        getHirpcVersionBytes() {
      Object ref = hirpcVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hirpcVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEPATH_FIELD_NUMBER = 2;
    private volatile Object servicePath_;
    /**
     * <code>required string servicePath = 2;</code>
     * @return Whether the servicePath field is set.
     */
    public boolean hasServicePath() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string servicePath = 2;</code>
     * @return The servicePath.
     */
    public String getServicePath() {
      Object ref = servicePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          servicePath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string servicePath = 2;</code>
     * @return The bytes for servicePath.
     */
    public com.google.protobuf.ByteString
        getServicePathBytes() {
      Object ref = servicePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        servicePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICENAME_FIELD_NUMBER = 3;
    private volatile Object serviceName_;
    /**
     * <code>required string serviceName = 3;</code>
     * @return Whether the serviceName field is set.
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string serviceName = 3;</code>
     * @return The serviceName.
     */
    public String getServiceName() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serviceName = 3;</code>
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEVERSION_FIELD_NUMBER = 4;
    private volatile Object serviceVersion_;
    /**
     * <code>optional string serviceVersion = 4;</code>
     * @return Whether the serviceVersion field is set.
     */
    public boolean hasServiceVersion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string serviceVersion = 4;</code>
     * @return The serviceVersion.
     */
    public String getServiceVersion() {
      Object ref = serviceVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serviceVersion = 4;</code>
     * @return The bytes for serviceVersion.
     */
    public com.google.protobuf.ByteString
        getServiceVersionBytes() {
      Object ref = serviceVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADER_FIELD_NUMBER = 5;
    private static final class HeaderDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  RequestPb.internal_static_com_hirpc_entity_RequestInner_HeaderEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> header_;
    private com.google.protobuf.MapField<String, String>
    internalGetHeader() {
      if (header_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      return header_;
    }

    public int getHeaderCount() {
      return internalGetHeader().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */

    public boolean containsHeader(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetHeader().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getHeader() {
      return getHeaderMap();
    }
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */

    public java.util.Map<String, String> getHeaderMap() {
      return internalGetHeader().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */

    public String getHeaderOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetHeader().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; header = 5;</code>
     */

    public String getHeaderOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetHeader().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PARAMETERTYPES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList parameterTypes_;
    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @return A list containing the parameterTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParameterTypesList() {
      return parameterTypes_;
    }
    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @return The count of parameterTypes.
     */
    public int getParameterTypesCount() {
      return parameterTypes_.size();
    }
    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    public String getParameterTypes(int index) {
      return parameterTypes_.get(index);
    }
    /**
     * <code>repeated string parameterTypes = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParameterTypesBytes(int index) {
      return parameterTypes_.getByteString(index);
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private volatile Object data_;
    /**
     * <code>optional string data = 7;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string data = 7;</code>
     * @return The data.
     */
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 7;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHirpcVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServicePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hirpcVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, servicePath_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serviceName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceVersion_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetHeader(),
          HeaderDefaultEntryHolder.defaultEntry,
          5);
      for (int i = 0; i < parameterTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, parameterTypes_.getRaw(i));
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hirpcVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, servicePath_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serviceName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serviceVersion_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetHeader().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        header__ = HeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, header__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameterTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(parameterTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParameterTypesList().size();
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestInner)) {
        return super.equals(obj);
      }
      RequestInner other = (RequestInner) obj;

      if (hasHirpcVersion() != other.hasHirpcVersion()) return false;
      if (hasHirpcVersion()) {
        if (!getHirpcVersion()
            .equals(other.getHirpcVersion())) return false;
      }
      if (hasServicePath() != other.hasServicePath()) return false;
      if (hasServicePath()) {
        if (!getServicePath()
            .equals(other.getServicePath())) return false;
      }
      if (hasServiceName() != other.hasServiceName()) return false;
      if (hasServiceName()) {
        if (!getServiceName()
            .equals(other.getServiceName())) return false;
      }
      if (hasServiceVersion() != other.hasServiceVersion()) return false;
      if (hasServiceVersion()) {
        if (!getServiceVersion()
            .equals(other.getServiceVersion())) return false;
      }
      if (!internalGetHeader().equals(
          other.internalGetHeader())) return false;
      if (!getParameterTypesList()
          .equals(other.getParameterTypesList())) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHirpcVersion()) {
        hash = (37 * hash) + HIRPCVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getHirpcVersion().hashCode();
      }
      if (hasServicePath()) {
        hash = (37 * hash) + SERVICEPATH_FIELD_NUMBER;
        hash = (53 * hash) + getServicePath().hashCode();
      }
      if (hasServiceName()) {
        hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
        hash = (53 * hash) + getServiceName().hashCode();
      }
      if (hasServiceVersion()) {
        hash = (37 * hash) + SERVICEVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getServiceVersion().hashCode();
      }
      if (!internalGetHeader().getMap().isEmpty()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeader().hashCode();
      }
      if (getParameterTypesCount() > 0) {
        hash = (37 * hash) + PARAMETERTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParameterTypesList().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestInner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestInner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestInner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestInner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestInner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestInner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestInner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestInner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestInner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestInner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestInner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestInner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestInner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hirpc.entity.RequestInner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hirpc.entity.RequestInner)
        RequestInnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestPb.internal_static_com_hirpc_entity_RequestInner_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetHeader();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableHeader();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestPb.internal_static_com_hirpc_entity_RequestInner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestInner.class, Builder.class);
      }

      // Construct using com.hirpc.protocol.protobuf.RequestPb.RequestInner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        hirpcVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        servicePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableHeader().clear();
        parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestPb.internal_static_com_hirpc_entity_RequestInner_descriptor;
      }

      @Override
      public RequestInner getDefaultInstanceForType() {
        return RequestInner.getDefaultInstance();
      }

      @Override
      public RequestInner build() {
        RequestInner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RequestInner buildPartial() {
        RequestInner result = new RequestInner(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hirpcVersion_ = hirpcVersion_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.servicePath_ = servicePath_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serviceVersion_ = serviceVersion_;
        result.header_ = internalGetHeader();
        result.header_.makeImmutable();
        if (((bitField0_ & 0x00000020) != 0)) {
          parameterTypes_ = parameterTypes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.parameterTypes_ = parameterTypes_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestInner) {
          return mergeFrom((RequestInner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestInner other) {
        if (other == RequestInner.getDefaultInstance()) return this;
        if (other.hasHirpcVersion()) {
          bitField0_ |= 0x00000001;
          hirpcVersion_ = other.hirpcVersion_;
          onChanged();
        }
        if (other.hasServicePath()) {
          bitField0_ |= 0x00000002;
          servicePath_ = other.servicePath_;
          onChanged();
        }
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000004;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasServiceVersion()) {
          bitField0_ |= 0x00000008;
          serviceVersion_ = other.serviceVersion_;
          onChanged();
        }
        internalGetMutableHeader().mergeFrom(
            other.internalGetHeader());
        if (!other.parameterTypes_.isEmpty()) {
          if (parameterTypes_.isEmpty()) {
            parameterTypes_ = other.parameterTypes_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureParameterTypesIsMutable();
            parameterTypes_.addAll(other.parameterTypes_);
          }
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000040;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasHirpcVersion()) {
          return false;
        }
        if (!hasServicePath()) {
          return false;
        }
        if (!hasServiceName()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestInner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestInner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object hirpcVersion_ = "";
      /**
       * <code>required string hirpcVersion = 1;</code>
       * @return Whether the hirpcVersion field is set.
       */
      public boolean hasHirpcVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string hirpcVersion = 1;</code>
       * @return The hirpcVersion.
       */
      public String getHirpcVersion() {
        Object ref = hirpcVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hirpcVersion_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string hirpcVersion = 1;</code>
       * @return The bytes for hirpcVersion.
       */
      public com.google.protobuf.ByteString
          getHirpcVersionBytes() {
        Object ref = hirpcVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hirpcVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hirpcVersion = 1;</code>
       * @param value The hirpcVersion to set.
       * @return This builder for chaining.
       */
      public Builder setHirpcVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hirpcVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hirpcVersion = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHirpcVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hirpcVersion_ = getDefaultInstance().getHirpcVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string hirpcVersion = 1;</code>
       * @param value The bytes for hirpcVersion to set.
       * @return This builder for chaining.
       */
      public Builder setHirpcVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hirpcVersion_ = value;
        onChanged();
        return this;
      }

      private Object servicePath_ = "";
      /**
       * <code>required string servicePath = 2;</code>
       * @return Whether the servicePath field is set.
       */
      public boolean hasServicePath() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string servicePath = 2;</code>
       * @return The servicePath.
       */
      public String getServicePath() {
        Object ref = servicePath_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            servicePath_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string servicePath = 2;</code>
       * @return The bytes for servicePath.
       */
      public com.google.protobuf.ByteString
          getServicePathBytes() {
        Object ref = servicePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          servicePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string servicePath = 2;</code>
       * @param value The servicePath to set.
       * @return This builder for chaining.
       */
      public Builder setServicePath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        servicePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string servicePath = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServicePath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        servicePath_ = getDefaultInstance().getServicePath();
        onChanged();
        return this;
      }
      /**
       * <code>required string servicePath = 2;</code>
       * @param value The bytes for servicePath to set.
       * @return This builder for chaining.
       */
      public Builder setServicePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        servicePath_ = value;
        onChanged();
        return this;
      }

      private Object serviceName_ = "";
      /**
       * <code>required string serviceName = 3;</code>
       * @return Whether the serviceName field is set.
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string serviceName = 3;</code>
       * @return The serviceName.
       */
      public String getServiceName() {
        Object ref = serviceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string serviceName = 3;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serviceName = 3;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceName = 3;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private Object serviceVersion_ = "";
      /**
       * <code>optional string serviceVersion = 4;</code>
       * @return Whether the serviceVersion field is set.
       */
      public boolean hasServiceVersion() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string serviceVersion = 4;</code>
       * @return The serviceVersion.
       */
      public String getServiceVersion() {
        Object ref = serviceVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceVersion_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string serviceVersion = 4;</code>
       * @return The bytes for serviceVersion.
       */
      public com.google.protobuf.ByteString
          getServiceVersionBytes() {
        Object ref = serviceVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceVersion = 4;</code>
       * @param value The serviceVersion to set.
       * @return This builder for chaining.
       */
      public Builder setServiceVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serviceVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceVersion = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serviceVersion_ = getDefaultInstance().getServiceVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceVersion = 4;</code>
       * @param value The bytes for serviceVersion to set.
       * @return This builder for chaining.
       */
      public Builder setServiceVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serviceVersion_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> header_;
      private com.google.protobuf.MapField<String, String>
      internalGetHeader() {
        if (header_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        return header_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableHeader() {
        onChanged();;
        if (header_ == null) {
          header_ = com.google.protobuf.MapField.newMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        if (!header_.isMutable()) {
          header_ = header_.copy();
        }
        return header_;
      }

      public int getHeaderCount() {
        return internalGetHeader().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; header = 5;</code>
       */

      public boolean containsHeader(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetHeader().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeaderMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getHeader() {
        return getHeaderMap();
      }
      /**
       * <code>map&lt;string, string&gt; header = 5;</code>
       */

      public java.util.Map<String, String> getHeaderMap() {
        return internalGetHeader().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; header = 5;</code>
       */

      public String getHeaderOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetHeader().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; header = 5;</code>
       */

      public String getHeaderOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetHeader().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearHeader() {
        internalGetMutableHeader().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; header = 5;</code>
       */

      public Builder removeHeader(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableHeader().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableHeader() {
        return internalGetMutableHeader().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; header = 5;</code>
       */
      public Builder putHeader(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableHeader().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; header = 5;</code>
       */

      public Builder putAllHeader(
          java.util.Map<String, String> values) {
        internalGetMutableHeader().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.LazyStringList parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParameterTypesIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          parameterTypes_ = new com.google.protobuf.LazyStringArrayList(parameterTypes_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @return A list containing the parameterTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParameterTypesList() {
        return parameterTypes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @return The count of parameterTypes.
       */
      public int getParameterTypesCount() {
        return parameterTypes_.size();
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @param index The index of the element to return.
       * @return The parameterTypes at the given index.
       */
      public String getParameterTypes(int index) {
        return parameterTypes_.get(index);
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the parameterTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParameterTypesBytes(int index) {
        return parameterTypes_.getByteString(index);
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @param index The index to set the value at.
       * @param value The parameterTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParameterTypes(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterTypesIsMutable();
        parameterTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @param value The parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParameterTypes(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterTypesIsMutable();
        parameterTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @param values The parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParameterTypes(
          Iterable<String> values) {
        ensureParameterTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameterTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameterTypes() {
        parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 6;</code>
       * @param value The bytes of the parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParameterTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterTypesIsMutable();
        parameterTypes_.add(value);
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <code>optional string data = 7;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string data = 7;</code>
       * @return The data.
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string data = 7;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 7;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 7;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        data_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hirpc.entity.RequestInner)
    }

    // @@protoc_insertion_point(class_scope:com.hirpc.entity.RequestInner)
    private static final RequestInner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestInner();
    }

    public static RequestInner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<RequestInner>
        PARSER = new com.google.protobuf.AbstractParser<RequestInner>() {
      @Override
      public RequestInner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestInner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestInner> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestInner> getParserForType() {
      return PARSER;
    }

    @Override
    public RequestInner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hirpc_entity_RequestInner_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hirpc_entity_RequestInner_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hirpc_entity_RequestInner_HeaderEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hirpc_entity_RequestInner_HeaderEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017RequestPb.proto\022\020com.hirpc.entity\"\367\001\n\014" +
      "RequestInner\022\024\n\014hirpcVersion\030\001 \002(\t\022\023\n\013se" +
      "rvicePath\030\002 \002(\t\022\023\n\013serviceName\030\003 \002(\t\022\026\n\016" +
      "serviceVersion\030\004 \001(\t\022:\n\006header\030\005 \003(\0132*.c" +
      "om.hirpc.entity.RequestInner.HeaderEntry" +
      "\022\026\n\016parameterTypes\030\006 \003(\t\022\014\n\004data\030\007 \001(\t\032-" +
      "\n\013HeaderEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001B(\n\033com.hirpc.protocol.protobufB\tRe" +
      "questPb"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hirpc_entity_RequestInner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hirpc_entity_RequestInner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hirpc_entity_RequestInner_descriptor,
        new String[] { "HirpcVersion", "ServicePath", "ServiceName", "ServiceVersion", "Header", "ParameterTypes", "Data", });
    internal_static_com_hirpc_entity_RequestInner_HeaderEntry_descriptor =
      internal_static_com_hirpc_entity_RequestInner_descriptor.getNestedTypes().get(0);
    internal_static_com_hirpc_entity_RequestInner_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hirpc_entity_RequestInner_HeaderEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
